# src/bazi.py
"""BaZi (八字) agent: pillars, element counting, 十神, and domain scoring.

Wu Xing generating cycle: Wood → Fire → Earth → Metal → Water → Wood
Wu Xing overcoming cycle: Wood → Earth → Water → Fire → Metal → Wood
"""

import math

from src.calendar_engine import gregorian_to_pillars
from src.tables import (
    HEAVENLY_STEMS,
    EARTHLY_BRANCHES,
    HIDDEN_STEMS,
    SEASONAL_STRENGTH,
    get_season,
)

# ---------------------------------------------------------------------------
# Wu Xing cycle definitions
# ---------------------------------------------------------------------------

# Generating cycle (相生): each element generates the next
# Wood→Fire→Earth→Metal→Water→Wood
_ELEMENTS = ["wood", "fire", "earth", "metal", "water"]

# element → element it generates
_GENERATES = {
    "wood":  "fire",
    "fire":  "earth",
    "earth": "metal",
    "metal": "water",
    "water": "wood",
}

# element → element it overcomes (相克)
# Wood→Earth→Water→Fire→Metal→Wood
_OVERCOMES = {
    "wood":  "earth",
    "earth": "water",
    "water": "fire",
    "fire":  "metal",
    "metal": "wood",
}

# Derived: element → element generated by it (i.e. element's parent in generating cycle)
_GENERATED_BY = {v: k for k, v in _GENERATES.items()}

# Derived: element → element overcome by it (i.e. what overcomes this element)
_OVERCOME_BY = {v: k for k, v in _OVERCOMES.items()}


def _sigmoid(x):
    """Sigmoid function mapping any real → (0, 1)."""
    return 1.0 / (1.0 + math.exp(-x))


class BaZiAgent:
    """BaZi agent: analyze a birth datetime and produce domain scores."""

    def analyze(self, dt):
        """Analyze a birth datetime.

        Args:
            dt: datetime.datetime

        Returns:
            dict with keys:
                pillars         — list of 4 (stem, branch) tuples
                element_counts  — dict {element: float}
                day_master      — element string
                day_master_strength — float in [0, 1]
                ten_gods        — dict {position_label: god_name}
                domain_scores   — dict {domain: float in [0, 1]}
        """
        pillars = gregorian_to_pillars(dt)
        element_counts = self._count_elements(pillars)
        day_stem_idx = pillars[2][0]
        day_master = HEAVENLY_STEMS[day_stem_idx]["element"]
        day_master_polarity = HEAVENLY_STEMS[day_stem_idx]["polarity"]
        day_master_strength = self._day_master_strength(
            day_master, pillars, element_counts
        )
        ten_gods = self._derive_ten_gods(day_stem_idx, day_master, day_master_polarity, pillars)
        domain_scores = self._score_domains(
            day_master, day_master_strength, ten_gods, element_counts
        )

        return {
            "pillars": pillars,
            "element_counts": element_counts,
            "day_master": day_master,
            "day_master_strength": day_master_strength,
            "ten_gods": ten_gods,
            "domain_scores": domain_scores,
        }

    # ------------------------------------------------------------------
    # Element counting
    # ------------------------------------------------------------------

    def _count_elements(self, pillars):
        """Count elements across all 8 characters + hidden stems.

        Each of the 4 stems contributes weight 1.0.
        Each of the 4 branches contributes its main element at full weight,
        plus hidden stem elements weighted by their 藏干 weights.
        Returns dict {element: float}.
        """
        counts = {e: 0.0 for e in _ELEMENTS}

        for stem_idx, branch_idx in pillars:
            # Stem element: full weight
            counts[HEAVENLY_STEMS[stem_idx]["element"]] += 1.0

            # Branch element (via its own element attribute): full weight
            counts[EARTHLY_BRANCHES[branch_idx]["element"]] += 1.0

            # Hidden stems in this branch
            for hidden_stem_idx, weight in HIDDEN_STEMS[branch_idx]:
                counts[HEAVENLY_STEMS[hidden_stem_idx]["element"]] += weight

        return counts

    # ------------------------------------------------------------------
    # Day master strength
    # ------------------------------------------------------------------

    def _day_master_strength(self, day_master, pillars, element_counts):
        """Compute day master strength in [0, 1].

        Combined = 0.5 * seasonal_strength + 0.5 * support_ratio
        """
        # Seasonal strength: determined by month branch (pillar index 1)
        month_branch = pillars[1][1]
        season = get_season(month_branch)
        seasonal = SEASONAL_STRENGTH[(day_master, season)]

        # Support ratio: count supporting elements vs. draining elements
        # Supporting: same element (比肩/劫财) + element that generates day master (印)
        # Draining: element day master generates (食伤) + element day master overcomes (财)
        #           + element that overcomes day master (官杀)
        supporting_elements = {day_master, _GENERATED_BY[day_master]}
        draining_elements = {
            _GENERATES[day_master],
            _OVERCOMES[day_master],
            _OVERCOME_BY[day_master],
        }

        # Exclude day master itself from the scoring (we measure external support)
        support_score = 0.0
        drain_score = 0.0
        total_external = 0.0

        for stem_idx, branch_idx in pillars:
            # Count stems and branches, but skip the day stem itself (index 2)
            stem_elem = HEAVENLY_STEMS[stem_idx]["element"]
            branch_elem = EARTHLY_BRANCHES[branch_idx]["element"]

            for elem, weight in [(stem_elem, 1.0), (branch_elem, 1.0)]:
                total_external += weight
                if elem in supporting_elements:
                    support_score += weight
                elif elem in draining_elements:
                    drain_score += weight

            # Hidden stems
            for hidden_stem_idx, w in HIDDEN_STEMS[branch_idx]:
                elem = HEAVENLY_STEMS[hidden_stem_idx]["element"]
                total_external += w
                if elem in supporting_elements:
                    support_score += w
                elif elem in draining_elements:
                    drain_score += w

        if total_external > 0:
            support_ratio = support_score / total_external
        else:
            support_ratio = 0.5

        return 0.5 * seasonal + 0.5 * support_ratio

    # ------------------------------------------------------------------
    # 十神 (Ten Gods)
    # ------------------------------------------------------------------

    def _ten_god(self, day_master, day_polarity, other_elem, other_polarity):
        """Derive the 十神 name for a given relationship.

        Args:
            day_master:    element of the day stem
            day_polarity:  polarity of the day stem ('yang' or 'yin')
            other_elem:    element of the other stem/branch
            other_polarity: polarity of the other stem/branch

        Returns:
            str — one of the 10 god names
        """
        same_polarity = (day_polarity == other_polarity)

        if other_elem == day_master:
            return "比肩" if same_polarity else "劫财"
        elif other_elem == _GENERATES[day_master]:
            # Element I generate
            return "食神" if same_polarity else "伤官"
        elif other_elem == _OVERCOMES[day_master]:
            # Element I overcome
            return "偏财" if same_polarity else "正财"
        elif other_elem == _OVERCOME_BY[day_master]:
            # Element that overcomes me
            return "七杀" if same_polarity else "正官"
        elif other_elem == _GENERATED_BY[day_master]:
            # Element that generates me
            return "偏印" if same_polarity else "正印"
        else:
            # Fallback (should not happen with a complete Wu Xing set)
            return "比肩"

    def _derive_ten_gods(self, day_stem_idx, day_master, day_polarity, pillars):
        """Derive 十神 for all stem and branch positions except the day stem itself.

        Returns:
            dict {label: god_name}
            Labels: 'year_stem', 'year_branch', 'month_stem', 'month_branch',
                    'day_branch', 'hour_stem', 'hour_branch'
        """
        labels = ["year", "month", "day", "hour"]
        gods = {}

        for i, (stem_idx, branch_idx) in enumerate(pillars):
            pillar = labels[i]

            # Stem (skip the day stem itself)
            if not (i == 2):
                stem_elem = HEAVENLY_STEMS[stem_idx]["element"]
                stem_pol = HEAVENLY_STEMS[stem_idx]["polarity"]
                gods[f"{pillar}_stem"] = self._ten_god(
                    day_master, day_polarity, stem_elem, stem_pol
                )
            # else: day stem is the day master itself, no god for it

            # Branch — use the branch's main element and polarity
            branch_elem = EARTHLY_BRANCHES[branch_idx]["element"]
            branch_pol = EARTHLY_BRANCHES[branch_idx]["polarity"]
            gods[f"{pillar}_branch"] = self._ten_god(
                day_master, day_polarity, branch_elem, branch_pol
            )

        return gods

    # ------------------------------------------------------------------
    # Domain scoring
    # ------------------------------------------------------------------

    def _god_strength(self, ten_gods, god_names):
        """Count how many positions contain any of the named gods.

        Returns a raw count (float).
        """
        return sum(1.0 for g in ten_gods.values() if g in god_names)

    def _score_domains(self, day_master, day_master_strength, ten_gods, element_counts):
        """Map BaZi analysis to 5 life domain scores, each in [0, 1].

        Scoring:
          career:        官星 (正官 + 七杀) strength, modulated by day master strength
          wealth:        财星 (正财 + 偏财) strength, modulated by day master strength
          relationships: 正财 + 正官 combined count
          health:        inverse of element balance variance (balanced = healthy)
          overall:       weighted average of above
        """
        n_positions = len(ten_gods)  # 7 positions (all except day stem)

        # Career: 官星 strength
        guan_count = self._god_strength(ten_gods, {"正官", "七杀"})
        # Normalize to [0,1]: raw score relative to total positions, sigmoid-centred
        career_raw = (guan_count / max(n_positions, 1)) * 2 - 0.5
        # Modulate: strong day master handles 官 better
        career_raw += 0.3 * (day_master_strength - 0.5)
        career = _sigmoid(career_raw * 3)

        # Wealth: 财星 strength
        cai_count = self._god_strength(ten_gods, {"正财", "偏财"})
        wealth_raw = (cai_count / max(n_positions, 1)) * 2 - 0.5
        wealth_raw += 0.3 * (day_master_strength - 0.5)
        wealth = _sigmoid(wealth_raw * 3)

        # Relationships: 正财 + 正官 (gender-neutral indicators of partnership)
        rel_count = self._god_strength(ten_gods, {"正财", "正官"})
        rel_raw = (rel_count / max(n_positions, 1)) * 2 - 0.5
        relationships = _sigmoid(rel_raw * 3)

        # Health: based on element balance — low variance = balanced = high health
        values = list(element_counts.values())
        total = sum(values)
        if total > 0:
            proportions = [v / total for v in values]
            mean_p = 1.0 / len(proportions)
            variance = sum((p - mean_p) ** 2 for p in proportions) / len(proportions)
            # Max variance when one element = 1.0, rest = 0.0 → var = 4*(0-0.2)^2/5 + (1-0.2)^2/5
            max_variance = 0.16  # approx max for 5 elements
            balance = 1.0 - min(variance / max_variance, 1.0)
        else:
            balance = 0.5
        health = balance  # already in [0, 1]

        # Overall: weighted average
        overall = _sigmoid(
            (0.25 * career_raw * 3)
            + (0.25 * wealth_raw * 3)
            + (0.25 * (rel_raw * 3))
            + (0.25 * (2 * health - 1))
        )

        return {
            "career": round(career, 8),
            "wealth": round(wealth, 8),
            "relationships": round(relationships, 8),
            "health": round(health, 8),
            "overall": round(overall, 8),
        }
