"""Shared configuration for reproducible emergence analyses."""

DEFAULT_SEED = 42
MSI_ARTIFACT_THRESHOLD = 2.0
NONLINEARITY_BOOTSTRAP_SAMPLES = 120
NONLINEARITY_CI_LEVEL = 0.95
NONLINEARITY_MIN_POINTS = 6
